export const SET_USER = "SET_USER";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const UI_FINISH_LOADING = "UI_FINISH_LOADING";
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_SHOW_TOAST = "UI_SHOW_TOAST";
export const UI_CLOSE_TOAST = "UI_CLOSE_TOAST";
export const UI_START_COMMENT_BUTTON = "UI_START_COMMENT_BUTTON";
export const UI_STOP_COMMENT_BUTTON = "UI_STOP_COMMENT_BUTTON";
export const UI_START_LOGIN_BUTTON = "UI_START_LOGIN_BUTTON";
export const UI_STOP_LOGIN_BUTTON = "UI_STOP_LOGIN_BUTTON";
export const UI_START_REGISTER_BUTTON = "UI_START_REGISTER_BUTTON";
export const UI_STOP_REGISTER_BUTTON = "UI_STOP_REGISTER_BUTTON";
export const UI_DISPLAY_VOTE_CARD = "UI_DISPLAY_VOTE_CARD";
export const UI_EXPAND_VOTE_CARD = "UI_EXPAND_VOTE_CARD";

export const STATE_DATA = "STATE_DATA";
export const SET_VOTE_CARD = "SET_VOTE_CARD";
